services:
  - type: web
    name: spotify-oauth-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=5000
    envVars:
      - key: FLASK_APP
        value: app/app.py
      - key: FLASK_ENV
        value: development
      - key: PORT
        value: 5000
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: SPOTIFY_REFRESH_TOKEN
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLASK_SECRET
        sync: false
