services:
  - type: web
    name: spotify-oauth-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.app  # updated to match your new structure
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: SPOTIFY_REFRESH_TOKEN
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLASK_SECRET
        sync: false
